package view;

import dao.ProductDAO;
import dao.OrderDAO;
import dao.PromotionDAO;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Promotion;


/**
 *
 * @author ADMIN
 */
public class OrderConfirm extends javax.swing.JFrame {
    OrderDAO order = new OrderDAO();
    ProductDAO productDAO = new ProductDAO();
    PromotionDAO dao = new PromotionDAO();
    DefaultTableModel model;
    double discountPercent = 0;
    /**
     * Creates new form OrderConfirm
     */
    public OrderConfirm(String orderId, String createdBy, 
                        String orderDate, String deliveryDate, 
                        String address, String note,
                        DefaultTableModel cartModel) {
        initComponents();
        setLocationRelativeTo(null); // Căn giữa khi khởi động
        loadTablePromotion();
        // Set dữ liệu vào textfield
        lblOrderId.setText(order.generateOrderId());
        lblCreatedBy.setText(createdBy);
        lblOrderDate.setText(orderDate);
        lblDeliveryDate.setText(deliveryDate);
        taAddress.setText(address);
        taNote.setText(note);

        // Copy dữ liệu từ cartModel sang tblOrderDetail
        DefaultTableModel confirmModel = (DefaultTableModel) tblCart.getModel();
        confirmModel.setRowCount(0); // xoá tất cả các dòng cũ trước khi thêm mới
        double total = 0;
        for (int i = 0; i < cartModel.getRowCount(); i++) {
            Object[] row = new Object[cartModel.getColumnCount()];
            for (int j = 0; j < cartModel.getColumnCount(); j++) {
                row[j] = cartModel.getValueAt(i, j);
            }
            confirmModel.addRow(row);

            // cột Thành tiền giả sử là cột cuối (index 4)
            total += Double.parseDouble(cartModel.getValueAt(i, 4).toString());
        }

        // Hiển thị tổng tiền
        lblTotal.setText("Tổng tiền: " + total);
    }
    
    //load bảng khuyến mãi
    private void loadTablePromotion() {
        try {
            List<Promotion> list = dao.getAllPromotions();
            model = (DefaultTableModel) tblPromotion.getModel();
            model.setRowCount(0);
            for (Promotion p : list) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getName(),
                    p.getDiscount(),
                    p.getStartDate(),
                    p.getEndDate(),
                    p.getDescription()
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
        }
    }
    
    //Cập nhật lại giá sau khi áp dụng khuyến mãi
    private void updateTotalWithDiscount() {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        double total = 0;

        // Tính tổng tiền gốc của đơn hàng
        for (int i = 0; i < model.getRowCount(); i++) {
            total += Double.parseDouble(model.getValueAt(i, 4).toString());
        }

        // Lấy giá trị giảm từ bảng khuyến mãi (nếu có chọn)
        int selectedRow = tblPromotion.getSelectedRow();
        double discountValue = 0;
        if (selectedRow != -1) {
            try {
                discountValue = Double.parseDouble(tblPromotion.getValueAt(selectedRow, 2).toString());
            } catch (NumberFormatException e) {
                discountValue = 0; // nếu dữ liệu lỗi, tránh crash
            }
        }

        // Tính tổng tiền cuối cùng sau khi trừ giảm giá
        double finalTotal = total - discountValue;
        if (finalTotal < 0) finalTotal = 0; // tránh âm

        // Cập nhật label hiển thị
        lblTotal.setText(String.format("Tổng tiền: %.2f (Giảm: %.2f)", finalTotal, discountValue));
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNote = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        btnComeBack = new javax.swing.JButton();
        lblOrderId = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        lblDeliveryDate = new javax.swing.JLabel();
        txtCreateBy = new javax.swing.JLabel();
        lblCreatedBy = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPromotion = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Xác nhận đơn hàng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã đơn hàng:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Người tạo: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày đặt:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ngày giao:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ghi chú:");

        taNote.setColumns(20);
        taNote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taNote.setRows(5);
        jScrollPane1.setViewportView(taNote);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phâm", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCart);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Tổng tiền: ");

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Thoát");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        taAddress.setColumns(20);
        taAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taAddress.setRows(5);
        jScrollPane3.setViewportView(taAddress);

        btnComeBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnComeBack.setText("Quay lại");
        btnComeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComeBackActionPerformed(evt);
            }
        });

        lblOrderId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblOrderDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblDeliveryDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCreateBy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCreatedBy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblPromotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Giảm giá", "Ngày bắt đầu", "Ngày kết thúc", "Miêu tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromotionMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPromotion);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Áp dụng khuyến mãi ");

        lblImage.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnComeBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirm)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(lblOrderId))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(txtCreateBy))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCreatedBy)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(40, 40, 40)
                                        .addComponent(lblDeliveryDate)
                                        .addGap(287, 287, 287))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(lblOrderDate))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(336, 336, 336))
                            .addComponent(jScrollPane4))
                        .addGap(35, 35, 35)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnComeBack)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblOrderId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCreateBy)
                            .addComponent(lblCreatedBy))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnCancel)
                            .addComponent(btnConfirm)
                            .addComponent(lblTotal))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblOrderDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblDeliveryDate))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            String orderId = order.generateOrderId();
            String createdBy = lblCreatedBy.getText();
            String orderDate = lblOrderDate.getText();
            String deliveryDate = lblDeliveryDate.getText();
            String address = taAddress.getText();
            String note = taNote.getText();
            double totalAmount = 0;

            DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                totalAmount += Double.parseDouble(model.getValueAt(i, 4).toString());
            }

            // Lấy giá trị khuyến mãi (nếu có)
            int selectedPromoRow = tblPromotion.getSelectedRow();
            double discountValue = 0;
            if (selectedPromoRow != -1) {
                discountValue = Double.parseDouble(tblPromotion.getValueAt(selectedPromoRow, 2).toString());
            }

            // Tính tổng tiền sau khuyến mãi
            double finalTotal = totalAmount - discountValue;
            if (finalTotal < 0) finalTotal = 0;

            OrderDAO orderDAO = new OrderDAO();

            // 1. Lưu Orders (đã trừ khuyến mãi)
            orderDAO.insertOrder(orderId, orderDate, deliveryDate, createdBy, address, note, finalTotal);

            // 2. Lưu Order_Details (đã trừ khuyến mãi theo tỷ lệ)
            for (int i = 0; i < model.getRowCount(); i++) {
                String detailId = orderDAO.generateOrderDetailId();
                String productId = model.getValueAt(i, 0).toString();
                double price = Double.parseDouble(model.getValueAt(i, 2).toString());
                int quantity = Integer.parseInt(model.getValueAt(i, 3).toString());
                double amount = Double.parseDouble(model.getValueAt(i, 4).toString());

                orderDAO.insertOrderDetail(detailId, orderId, productId, price, quantity, amount);
            }

            JOptionPane.showMessageDialog(this, "Đặt hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi lưu đơn hàng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblCart.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa sản phẩm này khỏi đơn hàng?", 
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
            model.removeRow(selectedRow);

            // Cập nhật lại tổng tiền
            double total = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                total += Double.parseDouble(model.getValueAt(i, 4).toString());
            }
            lblTotal.setText("Tổng tiền: " + total);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnComeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComeBackActionPerformed
        // Lấy thông tin user hiện tại (người đã đăng nhập)
        String createdBy = lblCreatedBy.getText();

        // Mở lại form OrderUser
        OrderUser orderUserForm = new OrderUser(createdBy);
        orderUserForm.setVisible(true);

        // Đóng form hiện tại
        this.dispose();   
    }//GEN-LAST:event_btnComeBackActionPerformed

    private void tblPromotionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromotionMouseClicked
        int selectedRow = tblPromotion.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy giá trị giảm giá từ cột thứ 3 (index = 2)
            Object discountObj = tblPromotion.getValueAt(selectedRow, 2);
            if (discountObj != null) {
                try {
                    discountPercent = Double.parseDouble(discountObj.toString());
                } catch (NumberFormatException e) {
                    discountPercent = 0;
                }
            } else {
                discountPercent = 0;
            }

            updateTotalWithDiscount();
        }
    }//GEN-LAST:event_tblPromotionMouseClicked

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
        int selectedRow = tblCart.getSelectedRow();
        if (selectedRow >= 0) {
            String id = tblCart.getValueAt(selectedRow, 0).toString();

            // Lấy thông tin sản phẩm từ DB
            String imagePath = productDAO.getImagePathById(id);

            if (imagePath != null && !imagePath.isEmpty()) {
                // Chuyển lại đường dẫn về đúng dạng Windows
                imagePath = imagePath.replace("\\\\", "\\");
                File imageFile = new File(imagePath);

                if (imageFile.exists()) {
                    ImageIcon icon = new ImageIcon(new ImageIcon(imageFile.getAbsolutePath())
                        .getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
                    lblImage.setIcon(icon);
                    lblImage.setText("");
                } else {
                    lblImage.setIcon(null);
                    lblImage.setText("Ảnh không tồn tại");
                }
            } else {
                lblImage.setIcon(null);
                lblImage.setText("Chưa có ảnh");
            }
        }
    }//GEN-LAST:event_tblCartMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnComeBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblDeliveryDate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextArea taNote;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblPromotion;
    private javax.swing.JLabel txtCreateBy;
    // End of variables declaration//GEN-END:variables
}
