package view;

import dao.DBConnection;
import dao.OrderDAO;
import model.Order;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.OrderDetail;


/**
 *
 * @author ADMIN
 */
public class OrderManagement extends javax.swing.JFrame {
    private OrderDAO orderDAO;

    /**
     * Creates new form OrderManagement
     */
    public OrderManagement() {
        initComponents();
        orderDAO = new OrderDAO();
        loadOrders();
        setupStatisticComboBox();
    }
    
    // 1. Nạp dữ liệu Order vào bảng orderTable
    private void loadOrders() {
        List<Order> list = OrderDAO.getAllOrders();
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        for (Order o : list) {
            model.addRow(new Object[]{
                o.getId(),
                o.getOrderDate(),
                o.getOrderDelivery(),
                o.getCreatedBy(),  // thêm tên user
                o.getNote(),
                o.getTotalAmount()
            });
        }
        // clear detail table
        ((DefaultTableModel) tableOrderDetail.getModel()).setRowCount(0);
    }
    
    // Ví dụ trong JFrame hiển thị chi tiết đơn hàng
    private void loadOrderDetails(String orderId) {
        // Lấy model của bảng
        DefaultTableModel model = (DefaultTableModel) tableOrderDetail.getModel();
        model.setRowCount(0); // xóa các hàng cũ

        OrderDAO orderDAO = new OrderDAO();
        List<OrderDetail> details = orderDAO.getOrderDetails(orderId);

        for (OrderDetail od : details) {
            model.addRow(new Object[]{
                od.getOrderDetailId(),  // cột 1: Mã chi tiết đơn hàng
                od.getProductId(),      // cột 2: Mã sản phẩm
                od.getPrice(),          // cột 3: Đơn giá
                od.getQuantity(),       // cột 4: Số lượng
                od.getAmount()          // cột 5: Thành tiền (nếu có)
            });
        }

        // Gán model lại cho JTable
        tableOrderDetail.setModel(model);
    }
    
    private void setupStatisticComboBox() {
    // Thêm các lựa chọn thống kê
        cbxStatisticType.removeAllItems();
        cbxStatisticType.addItem("Ngày");
        cbxStatisticType.addItem("Tuần");
        cbxStatisticType.addItem("Tháng");
        cbxStatisticType.addItem("Năm");

        // Lắng nghe sự kiện khi thay đổi lựa chọn
        cbxStatisticType.addActionListener(e -> loadStatistics());

        // Mặc định chọn "Ngày"
        cbxStatisticType.setSelectedIndex(0);
    }
    
    private void loadStatistics() {
        try {
            String type = cbxStatisticType.getSelectedItem().toString();
            String queryType = "";

            switch (type) {
                case "Ngày":
                    queryType = "DAY";
                    break;
                case "Tuần":
                    queryType = "WEEK";
                    break;
                case "Tháng":
                    queryType = "MONTH";
                    break;
                case "Năm":
                    queryType = "YEAR";
                    break;
            }

            int orders = orderDAO.getTotalOrders(queryType);
            double revenue = orderDAO.getTotalRevenue(queryType);

            txtTotalOrders.setText("Số đơn: " + orders);
            txtTotalRevenue.setText("Doanh thu: " + revenue + " VND");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thống kê: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderDetail = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbxStatisticType = new javax.swing.JComboBox<>();
        txtTotalRevenue = new javax.swing.JTextField();
        txtTotalOrders = new javax.swing.JTextField();
        btnComeBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý đơn hàng");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn hàng", "Ngày đặt hàng", "Ngày giao hàng", "Người đặt", "Ghi chú", "Tổng số tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        tableOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã chi tiết", "Mã đơn hàng", "Mã sản phẩm", "Giá", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableOrderDetail);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Thống kê:");

        cbxStatisticType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxStatisticType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê" }));

        txtTotalRevenue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTotalOrders.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnComeBack.setText("Quay lại");
        btnComeBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComeBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnComeBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(cbxStatisticType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(923, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnComeBack)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxStatisticType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        int row = orderTable.getSelectedRow();
        if (row != -1) {
            String orderId = orderTable.getValueAt(row, 0).toString();
            loadOrderDetails(orderId);
        }
    }//GEN-LAST:event_orderTableMouseClicked

    private void btnComeBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComeBackActionPerformed
        this.dispose();
        AdminForm admin = new AdminForm();
        admin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComeBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComeBack;
    private javax.swing.JComboBox<String> cbxStatisticType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable tableOrderDetail;
    private javax.swing.JTextField txtTotalOrders;
    private javax.swing.JTextField txtTotalRevenue;
    // End of variables declaration//GEN-END:variables
}
